# Copyright 2020 SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Helm Add Repository
description: Runs helm repo add command.
inputs:
  name:
    description: The repository name.
    required: true
  url:
    description: The repository URL.
    required: true
  flags:
    description: |
      The flags to be passed to the Helm command. One flag per line is
      accepted.
    required: false
  update:
    description: Whether to run helm repo update or not.
    default: 'false'
outputs: {}
runs:
  using: composite
  steps:
  - run: |-
      set -o errexit -o nounset
      flags=(${{ inputs.flags }})
      helm repo add "${{ inputs.name }}" "${{ inputs.url }}" "${flags[@]}"
    shell: bash
  - run: |-
      set -o errexit
      if [[ "${{ inputs.update }}" == "true" ]]; then
        helm repo update
      fi
    shell: bash
